variables:
    PLUGIN_NAME: 'scieloModerationStages'
    
include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_4_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops/unit_tests.yml'
      - 'templates/groups/ops/cypress_tests.yml'

ops_integration_tests:
  rules:
    - when: never

code_formatting_check:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update && apt install composer -yqq
    - php -v
    - composer -v
    - composer config --global -- disable-ipv6 true