variables:
    PLUGIN_NAME: 'scieloModerationStages'
    
include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_4_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops/unit_tests.yml'
      - 'templates/groups/ops/cypress_tests.yml'

ops_integration_tests:
  rules:
    - when: never

code_formatting_check:
  before_script:
    - curl -I https://repo.packagist.org/p2/symfony/console.json